### ISSUE TITLE
Advice and guidance 

### ISSUE THREAD

**Issue by vyckou** [jfrog/log-analytics-elastic#6]
Hey, 

This is a very interesting initiative, which raises a few questions

- Is this project for demo purposes, or will it have a greater purpose? Unified support, analytics, monitoring etc
- we are running the medium size of the enterprise Artifactory and currently using filebeat to push logs to elastic search, should we consider to replace the current setup with this one?
- I would like to question unified-artifactory elastic search index, in the fluentd configuration. - nature and log scheme for different logs in artifactory have a very different nature. For example, console.log and access logs scheme have almost nothing in common, is it wise and does it make sense to put all logs into a single elastic search index?
- in the current fluentd configuration, currently, there is no timestamp in the index name - which almost makes impossible for effective log lifecycle (rotation and cleanup)

**Comment by peters95** [comment]
Hi @vyckou thanks for reaching out. I'll do my best to answer your questions above.

Is this project for demo purposes, or will it have a greater purpose? Unified support, analytics, monitoring etc

This project is part of the overall log analytics for JFrog platform and will be leveraged throughout all of JFrog. This project will be maintained for the foreseeable future.

We are running the medium size of the enterprise Artifactory and currently using filebeat to push logs to elastic search, should we consider to replace the current setup with this one?

This is up to you at the end of the day to determine whether the existing filebeat integration has all the features you need or not. The main reasons to switch that come to my mind are reliability (JFrog eating its own dog food keeps this integration more reliable imo) and features such as SIEM common data model mapping which integrates into Elastic's models without you having to do all the heavy lifting. For these two reasons you may want to consider switching. The main downside currently is the installation path still has work to be wrapped up which is being prioritized for the engineering team to work on. 

I would like to question unified-artifactory elastic search index, in the fluentd configuration. - nature and log scheme for different logs in artifactory have a very different nature. For example, console.log and access logs scheme have almost nothing in common, is it wise and does it make sense to put all logs into a single elastic search index?

I'll reach out to our engineering resource on. this question and provide a follow up. This seems like a valid feature request /enhancement.

in the current fluentd configuration, currently, there is no timestamp in the index name - which almost makes impossible for effective log lifecycle (rotation and cleanup)

This should be a bug will create an internal bug ticket to track this. Other vendor integrations such as Splunk provide this.

**Comment by vyckou** [comment]
@peters95 

Thanks for so prompt answer.
it is extremely good to read, that it will be recommended & standard for "unified" jfrog monitoring.
As indeed lots of users/customers were reverse engineering your logs and its schemas to ingest it to the Elastic as well as setting up grafana dashboards for making logs seen as metrics.

For now Filebeat and ingest pipelines in the Elastic does the job for us, but for every single Artifactory major version bump, we need to invest some time to catch up with the logging compatibility changes. So we will definitely move to this setup, as soon, as it will become a "stable" version
 
Personally fluentD installation and Elastic search setup, at least for us, doesn't bring any issues, as we are running large clusters with Elastic, which doesn't fit into K8s setups and fluentD installation is not a big either. For other folks, I think, helms will be very appreciated.

Anyways, as the main focus for such project - personally, I see a definition of the logging files and respective log message formats

Recommendation:  common view with https://github.com/jfrog/log-analytics-prometheus would be awesome. As this is half of the jfrog observation story, I suppose

**Comment by peters95** [comment]
@vyckou thank you for your suggestions. also appreciate your feedback in these matters.

You are correct future updates will include helm charts & JFrog metrics to prometheus. These repos will be regularly maintained and updated going forward w/ feature enhancements and bug fixes. Thanks!
